version = 0.1

[default.deploy.parameters]
stack_name = "grand-river-current"
resolve_s3 = true
s3_prefix = "grand-river-current"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
